# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tom conroy
email: tom@conroy.com.au
description: > # this means to ignore newlines until "baseurl:"
  making web things
baseurl: ""
url: "http://tom.conroy.com.au"

# Build settings
markdown: kramdown